-- 코드를 입력하세요
SELECT B.AUTHOR_ID,
        A.AUTHOR_NAME,
        B.CATEGORY,
        SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
        
    FROM BOOK B ,
        AUTHOR A ,
        BOOK_SALES BS
        
    WHERE 
    
        B.AUTHOR_ID = A.AUTHOR_ID
        AND B.BOOK_ID = BS.BOOK_ID
        AND EXTRACT(MONTH FROM BS.SALES_DATE) ='1'
        
    GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
    ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC