-- 코드를 입력하세요
SELECT I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
    FROM REST_REVIEW R,
    REST_INFO I
    WHERE 1=1 
        AND R.REST_ID = I.REST_ID
        AND ADDRESS LIKE '서울%'
    GROUP BY I.REST_ID,I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS
    ORDER BY SCORE DESC, FAVORITES DESC
        
        