-- 코드를 입력하세요
SELECT A.REST_ID,
        A.REST_NAME,	
        A.FOOD_TYPE,
        A.FAVORITES,
        A.ADDRESS,
        ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
    FROM REST_INFO A,
        REST_REVIEW B
    WHERE A.REST_ID = B.REST_ID 
    GROUP BY  A.REST_ID,
    A.REST_NAME,
    A.FOOD_TYPE,
    A.FAVORITES,
    A.ADDRESS
    HAVING A.ADDRESS LIKE '서울%'
    ORDER BY 6 DESC, 4 DESC
    
    