-- -- 코드를 입력하세요
SELECT * 
    FROM (
    SELECT  EXTRACT(YEAR FROM SALES_DATE) AS YEAR
    ,EXTRACT(MONTH FROM SALES_DATE) AS MONTH
    ,U.GENDER
    ,COUNT(DISTINCT(O.USER_ID)) AS USERS
    FROM USER_INFO U
        ,ONLINE_SALE O
    WHERE 1=1 AND 
        U.USER_ID = O.USER_ID 
    GROUP BY 
        EXTRACT(YEAR FROM SALES_DATE)
        ,EXTRACT(MONTH FROM SALES_DATE)
        ,U.GENDER
    HAVING U.GENDER IS NOT NULL
    ORDER BY 1,2,3
    )
    



