-- 코드를 입력하세요
SELECT
    TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR,
    EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH,
    U.GENDER,
    COUNT(DISTINCT(O.USER_ID)) AS USERS
    FROM
        USER_INFO U,
        ONLINE_SALE O 
    WHERE 1=1 
        AND U.USER_ID= O.USER_ID
    GROUP BY 
         TO_CHAR(O.SALES_DATE, 'YYYY'),
         EXTRACT(MONTH FROM O.SALES_DATE),
         U.GENDER
         HAVING U.GENDER IS NOT NULL
    ORDER BY 1,2,3

-- SELECT * 
--     FROM 
--         USER_INFO U,
--         ONLINE_SALE O 
--     WHERE 1=1 
--         AND U.USER_ID= O.USER_ID
        