-- 코드를 입력하세요
SELECT
    WAREHOUSE_ID,
    WAREHOUSE_NAME,
    ADDRESS,
    CASE WHEN FREEZER_YN IS NULL 
    THEN 'N'
    WHEN FREEZER_YN = 'Y' 
    THEN 'Y'
    ELSE 'N'
    END FREEZER_YN
    
FROM FOOD_WAREHOUSE
WHERE 1=1 
    AND ADDRESS LIKE '경기도%'
    