-- -- 코드를 입력하세요
-- SELECT *
-- FROM (SELECT I.NAME,
--     I.DATETIME
--     FROM ANIMAL_INS I,
--         ANIMAL_OUTS O
--     WHERE 1=1 
--         AND I.ANIMAL_ID = O.ANIMAL_ID
--         AND O.NAME IS NOT NULL
    
--     ORDER BY 2 ASC)
-- WHERE ROWNUM<4
SELECT *
FROM (SELECT a.NAME, a.DATETIME
      FROM ANIMAL_INS a LEFT JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID
      WHERE b.ANIMAL_ID IS NULL
      ORDER BY a.DATETIME
     )
WHERE ROWNUM < 4;