-- 코드를 입력하세요
SELECT 
    EXTRACT(MONTH FROM START_DATE) AS MONTH
    ,CAR_ID 
    ,COUNT(CAR_ID) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 1=1 
        AND CAR_ID IN (
        
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE '2022-08' <= TO_CHAR(START_DATE,'YYYY-MM') AND
            '2022-10' >=TO_CHAR(START_DATE, 'YYYY-MM')
            GROUP BY CAR_ID HAVING  COUNT(CAR_ID) >=5 
        
        )
        AND '2022-08' <= TO_CHAR(START_DATE,'YYYY-MM') AND
            '2022-10' >=TO_CHAR(START_DATE, 'YYYY-MM')
     GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
        HAVING COUNT(CAR_ID)>0 
     ORDER BY 1 ASC,2 DESC